Rove/Rove/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from dashboard import apis
from dashboard import views
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
	path('savemap', apis.saveMap),
	path('getdata', apis.getMapData),
	path('deletemapshape', apis.deleteMapShapes),
	path('editprofile', apis.editProfile),
	path('appLogin',apis.appLogin),
	path('login',obtain_auth_token,name="login"),
	path('appLogout',apis.logout),
	path('appRegistration',apis.appRegistration),
	path('tip_detail',apis.tip_detail),
	path('driver_detail', apis.driver_detail),
	path('custom_headers',apis.custom_headers),
	path('editpic',views.Editprofilepic),
	path(r'api/token',TokenObtainPairView.as_view()),
	path('api/token/refresh/',TokenRefreshView.as_view()),
	path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
	path('ratings/', include('star_ratings.urls', namespace='ratings')),
	path('rideHistory',apis.rideHistory),
	path('logout',apis.logout),
	path('payment',apis.payment),
	path('CardSave',apis.CardSave),
	path('intialstatebooking',apis.intialstatebooking),
	path('Startstatebooking',apis.Startstatebooking),
	path('Cancelbooking',apis.Cancelbooking),
	path('Sendrequest',apis.Sendrequest),
	path('lostreport',apis.lostreport),
	path('Contactus',apis.Contactus),
	path('driverContact',apis.driverContact),
	path('rating',apis.rating),
	path('promocode',apis.promocode),
	path('FAqs',apis.FAqs),
	path('go_online',apis.go_online),
	path('go_offline',apis.go_offline),
	path('FoundLostItem', apis.FoundLostItem),
	path('driverpastrides', apis.driverpastrides),
	path('ridehisrory', apis.ridehisrory),
	path('driverlist', apis.driverlist),
	path('acceptride', apis.acceptride),
	path('rejectride', apis.rejectride),
	path('addtaxinumber', apis.addtaxinumber),
	path('starttrip', apis.starttrip),
	path('endtrip', apis.endtrip),
	path('messagesApi',apis.messagesApi),
	path('locationLatLong',apis.locationLatLong),

]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Rove/dashboard/urls.py
from django.urls import path, include
from dashboard import views
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView, TemplateView
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('home/', HomePage.as_view(), name='home'),
    path('login/', DashboardLogin.as_view(), name='login'),
    # path('add-user/', AddUser.as_view(), name='add-user'),
    path('logout/', Logout.as_view(), name='logout'),
    # path('game-users/', GameAppUsers.as_view(), name='game-users'),
    # path('add_game_use/r', AddGameUsers.as_view(), name="add_game_user"),
    # path('edit-game-users/<user_id>/', EditGameUsers.as_view(), name='edit_game_users'),
    # path('delete-game-user/<user_id>/', DeleteGameUser.as_view(), name='delete_game_user'),
    path('add_staff/', AddStaff.as_view(), name="add_staff"),
    path('edit_admin/<user_id>/', EditAdmin.as_view(), name="edit_admin"),
    path('delete_admin/<user_id>/', DeleteAdmin.as_view(), name="delete_admin"),
    # path('delete_staff/<user_id>/', DeleteStaffUser.as_view(), name="delete_staff"),
    # path('staff_list/', StaffUserList.as_view(), name="staff_list"),
    # path('edit_staff/<user_id>/', EditStaffUser.as_view(), name="edit_staff"),
    # path('role_list/', RoleList.as_view(), name="role_list"),
    # path('add_role/', AddRole.as_view(), name="add_role"),
    # path('edit_role/<group_id>/', EditRole.as_view(), name="edit_role"),
    # path('delete_role/<group_id>/', DeleteRole.as_view(), name="delete_role"),
	path('add_vechicle/', addVehicle.as_view(), name="add_vechicle"),
	path('vechicle/', vechicleListing.as_view(), name="vechicle_listing"),
	path('delete_vechicle/<id>', vehicleDelete.as_view(), name="vechicle_delete"),
	path('edit_vechicle/', vehicleEdit.as_view(), name="vechicle_edit"),
	
	path('add_promocode/', addPromocode.as_view(), name="add_promocode"),
	path('promocode/', promocodeListing.as_view(), name="promocode_listing"),
	path('delete_promocode/<id>', promocodeDelete.as_view(), name="promocode_delete"),
	path('edit_promocode/', promocodeEdit.as_view(), name="promocode_edit"),
	
	path('add_driver/', addDriver.as_view(), name="add_driver"),
	path('driver/', driverListing.as_view(), name="driver_listing"),
	path('delete_driver/<id>', driverDelete.as_view(), name="driver_delete"),
	path('edit_driver/', driverEdit.as_view(), name="driver_edit"),
	
	path('add_zone/', addZone.as_view(), name="add_zone"),
	path('zone/', zoneListing.as_view(), name="zone_listing"),
	path('delete_zone/<id>', zoneDelete.as_view(), name="driver_delete"),
	path('edit_zone/', zoneEdit.as_view(), name="zone_edit"),
	path('change_password/', changePassword.as_view(), name="change_password"),
	
	path('user_management/', ManagementUsers.as_view(), name='user_management'),
	path('add_user/', AddUsers.as_view(), name='add-user'),
	path('delete_user/<id>', deleteUser.as_view(), name="delete_user"),
	path('edit_user/', editUser.as_view(), name='edit_user'),
	path('reset_password/<str:code>', ResetPassword.as_view(), name='reset_password'),
	path('forget_password/', ForgotPassword.as_view(), name='forget-password'),
	path('role/', roleList.as_view(), name="role_list"),
    path('add_role/', AddRole.as_view(), name="add_role"),
    path('edit_role/', EditRole.as_view(), name="edit_role"),
    path('delete_role/<id>', DeleteRole.as_view(), name="delete_role"),
	path(r'api-token-auth/', CustomAuthToken.as_view()),

	
	path('permission/', permissionList.as_view(), name="permission_list"),
	path('add_permission/', addPermission.as_view(), name="add_permission"),
	path('delete_permission/<id>', deletePermission.as_view(), name="delete_permission"),
	path('edit_permission/', editPermission.as_view(), name="edit_permission"),

	path('create/', create_session),
	path('access', access_session),
	path('delete', delete_session),

]

Rove/dashboard/views.py
from rest_framework.views import APIView
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth import login as auth_login
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic.base import View,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

import datetime
from django.contrib.auth.hashers import check_password
from django.contrib.auth.hashers import make_password
from random import *
import random
from django.conf import settings
from django.core.mail import send_mail, EmailMultiAlternatives, EmailMessage
import json
from django.http import HttpResponse
from .models import Ride
# import StaffUserOnly
# import json
from .models import *
# Create your views here.

class StaffUserOnly(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            pass
        else:
            messages.error(request, 'You don\'t Have Permission To Access this,Please Login With Right Credentials')
            return HttpResponseRedirect('/dashboard/login')
        return super().dispatch(request, *args, **kwargs)


class HomePage(StaffUserOnly, View):
	template_name = 'dashboard/user_list.html'
	def get(self, request):
		ride = Ride.objects.all()
		ridecomp=Ride.objects.filter(ridestatus='COMPLETED').count()
		ridecancelled=Ride.objects.filter(ridestatus='CANCELLED').count()
		usercount=User.objects.filter(is_active='1').count()
		return render(request, self.template_name, locals())


class DashboardLogin(View):
    template_name = 'dashboard/login.html'
    try:
        def get(self, request):
            if not request.user.is_authenticated:
                if request.COOKIES.get('username') is not None:
                    username = request.COOKIES.get('username')
                    password = request.COOKIES.get('password')

                return render(request, self.template_name, locals())
            else:

                return HttpResponseRedirect('/dashboard/home')

        def post(self, request):
            if not request.user.is_authenticated:
                username = request.POST.get("username")
                password = request.POST.get("password")
                if password and username:
                    user = authenticate(username=username, password=password)
                    if user is not None:
                        if user.is_staff == True:
                            auth_login(request, user)
                            print(request.POST.get('remember_me'))
                            if (request.POST.get('remember_me') == '1'):


                                messages.success(request, 'You are successfully logged in1 ')
                                html = HttpResponseRedirect('/dashboard/home')

                                html.set_cookie('username', request.POST.get("username"), max_age = None)
                                html.set_cookie('password', request.POST.get("password"), max_age = None)

                                return html
                            else:
                                messages.success(request, 'You are successfully logged in1 ')
                                html = HttpResponseRedirect('/dashboard/home')
                                return html

                        else:
                            messages.error(request, 'you are not authorised for this')
                    else:
                        messages.error(request, 'Invalid credentials')
                        return HttpResponseRedirect('/dashboard/login')
                return render(request, self.template_name, locals())
            else:
                return HttpResponseRedirect('/dashboard/home')
    except Exception as e:
        raise e


class Logout(View):
    def get(self, request):
        logout(request)
        messages.success(request, 'You are successfully logged out.')
        return redirect('/dashboard/login')


class AddStaff(StaffUserOnly, TemplateView):
    template_name = 'dashboard/add_users.html'

    def get(self, request, *args, **kwargs):
        group_list = Group.objects.all()
        model_list = ContentType.objects.exclude(
            app_label__in=["auth", "contenttypes", "sessions", "social_django", "admin"])
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        role = request.POST.get('role')
        status = request.POST.get('status')
        email = request.POST.get('email')
        selected_models = request.POST.getlist('models[]')
        email = email.lower()

        try:
            User.objects.get(email=email)
            messages.error(request, 'User already exists with given email.')
        except User.DoesNotExist:
            user = User.objects.create_user(
                email=email,
                username=email,
                first_name=name,
                last_name=last_name,


            )

            if role == 'super_admin':
                user.is_superuser = True
                user.groups.clear()
                user.is_staff = True
                if status == "A":
                    user.is_active = True
                else:
                    user.is_active = False
                user.set_password(password)
                user.save()
                permission_list = Permission.objects.all()
                user.user_permissions.set(permission_list)
                user.save()
                messages.success(request, 'SuperAdmin entry done successfully.')
                return HttpResponseRedirect('/dashboard/home')
            else:
                user.is_staff = True
                if status == "A":
                    user.is_active = True
                else:
                    user.is_active = False
                user.set_password(password)
                user.save()

                group = Group.objects.get(id=role)
                group.user_set.add(user)
                group.save()
                permission_list = Permission.objects.filter(content_type_id__in=selected_models)
                user.user_permissions.set(permission_list)
                user.save()
                messages.success(request, 'Staff entry done successfully.')
                return HttpResponseRedirect('/dashboard/staff_list')


class EditAdmin(StaffUserOnly, TemplateView):
    template_name = 'dashboard/edit_admin_user.html'

    def get(self, request, *args, **kwargs):
        user_id = kwargs.get('user_id')
        user = User.objects.get(id=user_id)
        user_groups = user.groups.all()
        current_id = 0
        if user_groups:
            current_id = user_groups[0].id
        groups = Group.objects.all()
        model_items = ContentType.objects.exclude(
            app_label__in=["auth", "contenttypes", "sessions", "social_django", "admin"])
        selected_permissions = set(
            Permission.objects.filter(user=user_id).values_list('content_type__model', flat=True).distinct())
        model_list = map(lambda model_item: {"id": model_item.id, "name": model_item.name,
                                             "slug": (model_item.name).replace(" ", "")}, model_items)
        return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        user_id = kwargs.get('user_id')
        name = request.POST.get('name')
        last_name = request.POST.get('last_name')
        new_pass = request.POST.get('password')
        role = request.POST.get('role')
        status = request.POST.get('status')
        email = request.POST.get('email')
        selected_models = request.POST.getlist('models[]')
        email = email.lower()

        try:
            user = User.objects.get(id=user_id)
            user.first_name = name
            user.last_name = last_name
            # user.username=email
            user.email = email
            if status == "A":
                user.is_active = True
            else:
                user.is_active = False
            user.save()

            if role == 'super_admin':
                user.is_superuser = True
                user.is_staff = True
                permission_list = Permission.objects.all()
                user.user_permissions.set(permission_list)
                user.save()
                messages.success(request, 'Admin details successfully edited.')
                return HttpResponseRedirect('/dashboard/home')
            else:
                user.is_superuser = False
                user.groups.clear()
                group = Group.objects.get(id=role)
                group.user_set.add(user)
                group.save()
                permission_list = Permission.objects.filter(content_type_id__in=selected_models)
                user.user_permissions.set(permission_list)
                user.save()
                messages.success(request, 'Admin details successfully edited.')
                return HttpResponseRedirect('/dashboard/staff_list')

            if new_pass:
                user.set_password(new_pass)
                user.save()
                messages.success(request, 'Admin details successfully edited.')
                return HttpResponseRedirect('/dashboard/home')

        except Exception as e:
            print(str(e))
            messages.error(request, 'Oops Something went wrong.')
            return HttpResponseRedirect('/dashboard/edit_admin/' + str(user_id))


class DeleteAdmin(StaffUserOnly, View):

Rove/dashboard/templates/dashboard/add_tournament_type.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %} Staff User List {% endblock %}
{% block head %}

{% endblock %}
{% block content %}
  
<section class="content container-fluid">
  <!-- <div class="alert alert-danger text-center" role="alert" style="display: none;">
  </div> -->
  {% if messages %}
  {% for message in messages %}
  <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
  {% endfor %}
  {% endif %}
  <div class="manage_admin">
   <div class="add_min d-flex justify-content-between"> 
    
    <h3>Add Tournament Type</h3>
  </div>
  <form action="{% url 'dashboard:add_tournament_type' %}" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-12 col-sm-6 col-md-6">
        <div class="form-group" id="add-role-error">
          <label>*Tournament Type</label>
          <input type="text" class="form-control" name="type_name" id="type_name" maxlength="50">
        </div>
        <button type="submit" class="edit register btn btn-success" id="add_type_btn"><sapn><i class="fa fa-check" aria-hidden="true"></i></sapn> Save</button>
        <a href="/dashboard/tournament-types">
        <button type="button" class="delete btn btn-orange"><span><i class="fa fa-ban" aria-hidden="true"></i></span> Cancel
        </button></a>
      </form>
    </div>
  </section>
 
     {% endblock %}
  {% block js %}
 <script>
    $('#add_type_btn').on("click", function(e) {
    // e.preventDefault();
    var type_name = $("#type_name").val();
    var validationError=false;
    var paras = document.getElementsByClassName('errors');
    while(paras[0])
      paras[0].parentNode.removeChild(paras[0]);
    if(type_name=='' || type_name==null){
      var x = document.createElement("LABEL");
      x.style.color = 'red';
      x.className='errors';
      x.innerHTML="Name can't be empty !";
      document.getElementById('add-role-error').appendChild(x);
      validationError=true;
      return false;
    }

    return true;
  });

  // $('.delete').on('click', function() {
  //   window.history.back();
  // });
</script>
{% endblock %}

Rove/dashboard/templates/dashboard/driver_listbk.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %} Add Game User {% endblock %}
{% block head %}

{% endblock %}
{% block content %}

  <section class="content container-fluid">
   <!--  <div class="alert alert-danger text-center" role="alert" style="display: none;">
    </div> -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <div class="manage_admin">
     <div class="add_min d-flex justify-content-between"> 
      <h3>Driver List</h3>
    </div>

	<div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Add Driver</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
	  <form action="{% url 'dashboard:add_driver' %}" method="post" id="driveradd">
				{% csrf_token %}
      {% csrf_token %}
				<div class="modal-body mx-3">
				<div class="md-form mb-5">


				  <label data-error="wrong" data-success="right" for="firstname">First Name</label>
				  <input type="text" id="firstname" name ="firstname" class="form-control validate">
				</div>
				<div class="md-form mb-5">
				   <label data-error="wrong" data-success="right"  for="lastname">Last Name</label>
				  <input type="text" id="lastname" name="lastname" class="form-control validate">
			   
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="email">Email</label>
				  <input type="text" id="email" name="email" class="form-control validate">
			   
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="phonenumber">Phone Number</label>
				  <input type="text" id="phonenumber" name="phonenumber" maxlength="10" class="form-control validate">
				 
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="streetaddress">Street Address</label>
				  <input type="text" id="streetaddress" name="streetaddress" class="form-control validate">
				 
				</div>
		        <div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="city">City</label>
				  <input type="text" id="city" name="city" class="form-control validate">
				 
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="state">State</label>
				  <input type="text" id="state" name="state" class="form-control validate">
				 
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="zipcode">Zipcode</label>
				  <input type="text" id="zipcode" name="zipcode"  maxlength="6" class="form-control validate">
				 
				</div>
			  </div>
			 
			  <div class="modal-footer d-flex justify-content-center">
			  
			  <input type="submit" class="register-user  btn btn-success" value="Save">

			  </div>
	   </form>
    </div>
  </div>
</div>





	<div class="modal fade" id="edit_Modal" role="dialog">
      <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content ext-pad-spc">
          <div class="modal-content-outline">
              <div class="modal-header cus-mod-head">
                <button type="button" class="close cus-modal-crose" data-dismiss="modal">&times;</button>
                <h4 class="text-center">Edit Promocode</h4>
              </div>
				<form action="/dashboard/edit_driver/" method="post" id="driveredit">
				{% csrf_token %}
				<div class="modal-body mx-3">
				<div class="md-form mb-5">


				  <label data-error="wrong" data-success="right" for="firstname">First Name</label>
				  <input type="text" id="editfirstname" name ="firstname" class="form-control validate">
			   <input type="hidden" id="editid" name ="editid" class="form-control validate">
				</div>
				<div class="md-form mb-5">
				   <label data-error="wrong" data-success="right"  for="lastname">Last Name</label>
				  <input type="text" id="editlastname" name="lastname" class="form-control validate">
			   
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="email">Email</label>
				  <input type="text" id="editemail" name="email" class="form-control validate">
			   
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="phonenumber">Phone Number</label>
				  <input type="text" id="editphonenumber" name="phonenumber" maxlength="10" class="form-control validate">
				 
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="streetaddress">Street Address</label>
				  <input type="text" id="editstreetaddress" name="streetaddress" class="form-control validate">
				 
				</div>
		        <div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="city">City</label>
				  <input type="text" id="editcity" name="city" class="form-control validate">
				 
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="state">State</label>
				  <input type="text" id="editstate" name="state" class="form-control validate">
				 
				</div>
				<div class="md-form mb-5">
				  <label data-error="wrong" data-success="right"  for="zipcode">Zipcode</label>
				  <input type="text" id="editzipcode" name="zipcode"  maxlength="6" class="form-control validate">
				 
				</div>
			  </div>
			 
			  <div class="modal-footer d-flex justify-content-center">
			  
			  <input type="submit" class="register-user  btn btn-success" value="Save">

			  </div>
			   </form>
                  </div>
             
          </div>
        </div>
    </div>




<div class="text-center">
  <a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalRegisterForm">+ Driver</a>
</div>
	
	
   <table border="1" class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
		<th> S.No</th>  
		<th> First Name</th>  
		<th> Last Name</th>  
		<th>Email</th>  
		<th>Phone Number</th> 
		<th>Street Address</th> 
		<th>City</th> 
		<th>State</th> 
		<th>Zipcode</th> 		
		<th>Action</th> 		
    </tr>  
    </thead>  
    <tbody>


{% for show in driver %}  
    <tr>  
        <td id="id_{{ show.id }}"> {{ forloop.counter }}</td>  
        <td id="firstname_{{ show.id }}">{{ show.first_name }}</td>  
        <td id="lastname_{{ show.id }}">{{ show.last_name }}</td>  
        <td id="email_{{ show.id }}">{{ show.email }}</td>  
		<td id="phonenumber_{{ show.id }}">{{ show.phonenumber }}</td> 
		<td id="streeaddress_{{ show.id }}">{{ show.stree_address }}</td>
		<td id="city_{{ show.id }}">{{ show.city }}</td>
		<td id="state_{{ show.id }}">{{ show.state }}</td>
		<td id="zipcode_{{ show.id }}">{{ show.zipcode }}</td>
        <td>  

       <button type="button" class="primary-btn page-sec-edt-btn editdriver" id='edit_{{ show.id }}'  data-toggle="modal" data-target="#edit_Modal"><i class="fa fa-edit"></i></button>
        <a href="/dashboard/delete_driver/{{ show.id }}" class="deletebutton">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table> 
</div>
</section>
<!-- /.content -->




{% endblock %}
{% block js %}

<script>
  $('.delete').on('click', function() {
    window.history.back();
  });
  
  $(document).ready(function(){
  $(".deletebutton").click(function(){
    if (!confirm("Do you want to delete")){
      return false;
    }
  });
  

     $('.editdriver').click(function(){
		var el = this;
		var id = this.id;
		var splitid = id.split("_");
		var editid = splitid[1];
		$("#editfirstname").val($.trim($("#firstname_"+editid).text()));
		$("#editlastname").val($.trim($("#lastname_"+editid).text()));
		$("#editemail").val($.trim($("#email_"+editid).text()));
		$("#editphonenumber").val($.trim($("#phonenumber_"+editid).text()));
		$("#editstreetaddress").val($.trim($("#streeaddress_"+editid).text()));
		$("#editcity").val($.trim($("#city_"+editid).text()));
		$("#editstate").val($.trim($("#state_"+editid).text()));
		$("#editzipcode").val($.trim($("#zipcode_"+editid).text()));
		
        $("#editid").val(editid);
		
		
    
    });
	
	
	
	 $( "#driveredit" ).validate({
          rules: {
            firstname: {
              required: true,
             
            },
			lastname: {
              required: true,
             
            },
			email: {
              required: true,
             
            },
			phonenumber: {
              required: true,
             
            },
			streeaddress: {
              required: true,
             
            },
			city: {
              required: true,
             
            },
			state: {
              required: true,
             
            },
			zipcode: {
              required: true,
             
            }
			
          }
        });
		
		$( "#driveradd" ).validate({
         
             rules: {
            firstname: {
              required: true,
             
            },
			lastname: {
              required: true,
             
            },
			email: {
              required: true,
			  email:true,
             
            },
			phonenumber: {
              required: true,
             
            },
			streeaddress: {
              required: true,
             
            },
			city: {
              required: true,
             
            },
			state: {
              required: true,
             
            },
			zipcode: {
              required: true,
             
            }
          }
        });
        
   
});

$(document).ready(function(){
    $("#firstname").keypress(function(event){
        var inputValue = event.charCode;
        if(!(inputValue >= 65 && inputValue <= 120) && (inputValue != 32 && inputValue != 0)){
            event.preventDefault();
        }
    });
	
	 $("#lastname").keypress(function(event){
        var inputValue = event.charCode;
        if(!(inputValue >= 65 && inputValue <= 120) && (inputValue != 32 && inputValue != 0)){
            event.preventDefault();
        }
    });
	$("#editfirstname").keypress(function(event){
        var inputValue = event.charCode;
        if(!(inputValue >= 65 && inputValue <= 120) && (inputValue != 32 && inputValue != 0)){
            event.preventDefault();
        }
    });
	
	$("#editlastname").keypress(function(event){
        var inputValue = event.charCode;
        if(!(inputValue >= 65 && inputValue <= 120) && (inputValue != 32 && inputValue != 0)){
            event.preventDefault();
        }
    });
});


</script>




{% endblock %}

Rove/dashboard/templates/dashboard/role_list27-2.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %} Staff User List {% endblock %}
{% block head %}

{% endblock %}
{% block content %}

    <section class="content container-fluid">
      <div class="manage_admin">
        <div class="add_min d-flex justify-content-between"> 
    <h3>Manage Role</h3>
    <a href="{% url 'dashboard:add_role' %}"><button class="btn btn-success" id="add-user">Add New Role</button></a>
    </div>
    {% if groups %}
    <!-- <table class="table"> -->
      <div class="posting_table">
      <table id="example" class="table table-bordered" style="width:100%">
      <thead>   
        <tr>
          <th scope="col">Sr.No</th>
          <th scope="col">Role Name</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for group in groups %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ group.name|title }}</td>

          <td>
           <a href="{% url 'dashboard:edit_role' group.id %}"> <button type="submit" class="edit  btn btn-primary" data-id="{{ group.id }}"><sapn><i class="fa fa-pencil" aria-hidden="true"></i></sapn> Edit</button> </a>
      
            <a href="{% url 'dashboard:delete_role' group.id %}"><button type="submit" class="delete btn btn-danger" data-id="{{ group.id }}"><span><i class="fa fa-trash-o" aria-hidden="true"></i></span> Delete</button>
              </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <span>No records found</span>
    {% endif %}
      </div>
    </section>

  
  {% endblock %}